import os

# Define the folder structure as a list of paths
folders = [
    "app/Console",
    "app/Exceptions",
    "app/Helpers",
    "app/Http/Controllers/Auth",
    "app/Http/Middleware",
    "app/Http/Requests/FingerDevice",
    "app/Jobs",
    "app/Models",
    "app/Providers",
    "bootstrap/cache",
    "config",
    "database/factories",
    "database/migrations",
    "database/seeders",
    "public/assets/css",
    "public/assets/fonts",
    "public/assets/front/clock/css",
    "public/assets/front/clock/js",
    "public/assets/front/css",
    "public/assets/front/fonts/fontawesome",
    "public/assets/front/img/bg",
    "public/assets/front/img/demo",
    "public/assets/front/img/icons",
    "public/assets/front/js/vendor",
    "public/assets/icons/css",
    "public/assets/images/flags",
    "public/assets/images/gallery",
    "public/assets/images/products",
    "public/assets/images/services-icon",
    "public/assets/images/small",
    "public/assets/images/users",
    "public/assets/js",
    "public/assets/pages",
    "public/assets/scss",
    "public/js",
    "public/plugins/chartist/css",
    "public/plugins/chartist/js",
    "public/plugins/datatables/json",
    "public/plugins/jquery-ui",
    "public/plugins/peity-chart",
    "public/plugins/RWD-Table-Patterns/dist/css",
    "public/plugins/RWD-Table-Patterns/dist/js",
    "public/plugins/RWD-Table-Patterns/src/js",
    "public/plugins/RWD-Table-Patterns/src/less",
    "public/plugins/sweet-alert2",
    "public/plugins/tiny-editable",
    "public/plugins/x-editable/css",
    "public/plugins/x-editable/img",
    "public/plugins/x-editable/js",
    "public/svg",
    "resources/js/components",
    "resources/lang/en",
    "resources/sass",
    "resources/views/admin/fingerDevices",
    "resources/views/auth/passwords",
    "resources/views/includes",
    "resources/views/layouts",
    "routes",
    "storage/app/public",
    "storage/framework/cache/data",
    "storage/framework/sessions",
    "storage/framework/testing",
    "storage/framework/views",
    "storage/logs",
    "tests/Feature",
    "tests/Unit"
]

# Create each folder
for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("✅ Folder structure created successfully.")